/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.prime.avro.document;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface Document {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Document\",\"namespace\":\"com.prime.avro.document\",\"types\":[{\"type\":\"record\",\"name\":\"DocumentImpl\",\"fields\":[{\"name\":\"_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"title\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends Document {
    public static final org.apache.avro.Protocol PROTOCOL = com.prime.avro.document.Document.PROTOCOL;
  }
}